# Generated by Django 4.1 on 2022-08-10 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Action', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.DateField(default=django.utils.timezone.now)),
                ('length', models.CharField(default='60', max_length=4)),
                ('movie_trailer_link', models.URLField()),
                ('views', models.IntegerField(default=0)),
                ('movie_poster', models.ImageField(upload_to='movies/')),
                ('description', models.TextField()),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('movie_categories', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.categories')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-release_date',),
            },
        ),
    ]
