# Generated by Django 4.0.6 on 2022-07-28 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.DateField(default='timezone.now')),
                ('length', models.CharField(default='60', max_length=4)),
                ('movie_trailer_link', models.URLField()),
                ('actors', models.CharField(default='John Doe', max_length=50)),
                ('movie_categories', models.CharField(default='action', max_length=50)),
                ('movie_poster', models.ImageField(upload_to='movies/')),
                ('description', models.TextField()),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-release_date',),
            },
        ),
    ]
