# Generated by Django 4.0.6 on 2022-07-30 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movies_release_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Action', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movies',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='movie_categories',
        ),
        migrations.AlterField(
            model_name='movies',
            name='actors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.actor'),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_categories',
            field=models.ManyToManyField(to='movie.categories'),
        ),
    ]
