# Generated by Django 4.0.6 on 2022-07-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_actor_categories_movies_reviewed_movies_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='reviewed',
        ),
    ]
