# Generated by Django 4.0.6 on 2022-08-02 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_remove_movies_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='movie_categories',
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.categories'),
        ),
    ]
