# Generated by Django 4.0.6 on 2022-08-04 10:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0005_remove_movies_movie_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='favourites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL),
        ),
    ]
